import type { Metadata } from 'next'
import Header from './header/header'
import Footer from './footer/footer'
import styles from './layout.module.sass'
import fonts from '@/fonts'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={fonts.className}>
      <body>
        <div className={styles.app}>
          <Header />
          <div className={styles.content}>
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
