import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './header/header'
import Footer from './footer/footer'
import styles from './layout.module.sass'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className={styles.app}>
          <Header />
          <div className={styles.content}>
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}
